name: StreakVillage
options:
  bundleIdPrefix: com.foculoom
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "20260226.1"
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  StreakVillage:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/StreakVillage
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.streakvillage
        PRODUCT_NAME: "Streak Village"
        PRODUCT_MODULE_NAME: StreakVillage
        INFOPLIST_FILE: Sources/StreakVillage/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: "RZWT5WST77"
        CODE_SIGN_STYLE: Automatic

  StreakVillageTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests/StreakVillageTests
    dependencies:
      - target: StreakVillage
      - target: StreakVillageWatch
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.streakvillage.tests
        DEVELOPMENT_TEAM: "RZWT5WST77"
        CODE_SIGN_STYLE: Automatic
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Streak Village.app/Streak Village"
        BUNDLE_LOADER: "$(TEST_HOST)"


  StreakVillageWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: Sources/StreakVillageWatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.streakvillage.watchkitapp
        PRODUCT_NAME: "Village"
        INFOPLIST_FILE: Sources/StreakVillageWatch/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: "RZWT5WST77"
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "6.0"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "20260226.1"

schemes:
  StreakVillage:
    build:
      targets:
        StreakVillage: all
        StreakVillageTests: [test]
        StreakVillageWatch: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: StreakVillageTests
          randomExecutionOrder: true
      coverageTargets:
        - StreakVillage
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
